### ISSUE TITLE
Terraform Apply Validation Error

### ISSUE THREAD

**Issue by deurk** [stefanprodan/k8s-scw-baremetal#14]
Him

When I follow your guide, I end up facing an error on the `terraform apply` command:
`* data.scaleway_image.xenial: data.scaleway_image.xenial: StatusCode: 400, Type: invalid_request_error, APIMessage: Validation Error, Details: map[organization:[<MY_SCALEWAY_TOKEN_ACCESS_KEY> is not a valid UUID.]]`

Do you have any idea what it could come from? Maybe the scaleway API changed?
I'm using `v1.4.1` of the Scaleway provider (also tried with `v1.0.1`).

Thanks a lot for your insight.

**Comment by deurk** [comment]
(Being very new to Terraform, I hope I am not creating the issue myself)

**Comment by stephenmoloney** [comment]
I encountered this error too. 

I am wondering why others have not encountered the same error though and why the scaleway provider hasn't got this as an issue opened there - I think that is the right place for this issue.

https://github.com/terraform-providers/terraform-provider-scaleway

**Comment by deurk** [comment]
Thank you Stephen, your hint in MP helped. I will open an issue on the terraform scaleway provider module tracker :)
