### ISSUE TITLE
Seeking feedback on assignment of roles to worker nodes

### ISSUE THREAD

**Issue by stephenmoloney** [stefanprodan/k8s-scw-baremetal#17]
@stefanprodan Seeking some feedback as to whether this would make a useful PR.

I'm not sure if this will be useful to `k8s-scw-baremetal`.

Some of the changes I am starting to make to my own copy of `k8s-scw-baremetal` are quite opinionated but I thought that this change might be useful - although I'm not sure if the `node-role.kubernetes.io/worker` role is a kubernetes convention, maybe `node-role.kubernetes.io/node` is better.

https://github.com/stephenmoloney/k8s-scw-baremetal/commit/05a51a1001c2811146d1a2372e59ac6c3fc9b302

any thoughts?

**Comment by stefanprodan** [comment]
I don't see any use case for labelling the workers, Kubernetes scheduler will not run any workload on master anyway, this the default behaviour.

**Comment by stephenmoloney** [comment]
That's fair enough. It's probably a bit too opinionated to label the nodes with `node-role.kubernetes.io/node` by default.
