### ISSUE TITLE
[Suggestion] Add helm and tiller as defaults to the cluster

### ISSUE THREAD

**Issue by stephenmoloney** [stefanprodan/k8s-scw-baremetal#18]
I've added helm as a default to the cluster as I always use it.

I can make a PR if you like the idea @stefanprodan 

https://github.com/stefanprodan/k8s-scw-baremetal/compare/master...stephenmoloney:feature/provision_helm_tiller?expand=1

**Comment by stefanprodan** [comment]
Does Tiller works on ARM and ARM64?

**Comment by stephenmoloney** [comment]
Good catch.

I presumed it would reading this line 
https://github.com/helm/helm/blob/master/scripts/get#L63

But actually, it doesn't when I run it on scaleway as I get the error:
`helm No prebuilt binary for linux-armv7`

Seems like armv7 is not supported then.

**Comment by stephenmoloney** [comment]
I could do a conditional install - although it is not ideal, ie only install helm if ARCH != arm

**Comment by stefanprodan** [comment]
I plan to migrate this project to multi-arch node pools, the master will run on x86, and there will be 3 node pools one for each arch. At that point you could add Tiller with node affinity for x86.

**Comment by stephenmoloney** [comment]
Ok, I'll drop the idea of compiling for arm - it might not be worth the effort.

I had a similar thought for trying to create a multi-architecture cluster but for different reasons I think. 
I was thinking it would have been nice to have a multi-master with 3 x arm servers as master and then the worker nodes as either arm or x86 depending on one's choosing. The logic behind using 3 x arm servers as master was simply to keep the cost down but still have high availability. However, I've kinda changed my mind - the arm7 server seems a little bit underpowered for the master. It's a pity scaleway don't have something in between C1 and CS2 - maybe a `4 core arm64 with 4GB ram at an intermediate price point would have been nice.
