### ISSUE TITLE
Fixing version of terraform (0.10.X) and providers

### ISSUE THREAD

**Issue by perriea** [stefanprodan/k8s-scw-baremetal#2]
Hi,

### Terraform Versions ###
```
v0.11.X
```

### Terraform Command ### 
```
terraform apply -var nodes=3
```

### Terraform Error ###
```
data.scaleway_image.xenial: Refreshing state...

Error: Error running plan: 1 error(s) occurred:

* output.kubeadm_join_command: Resource 'data.external.kubeadm_join' does not have attribute 'result.command' for variable 'data.external.kubeadm_join.result.command'
```

### Comments ###

It seems that the problem has been shown to the Hashicorp team and there is quite a bit of activity on the subject:
- https://github.com/hashicorp/terraform/issues/16728
- https://github.com/hashicorp/terraform/issues/11806
- https://github.com/hashicorp/terraform/issues/17034

While waiting for it to be solved, I can via a PR fix the version of terraform a **0.10.8** :

**terraform.tf**
```
terraform {
  required_version = "<= 0.10.8"
}
```

Thanks !

**Comment by stefanprodan** [comment]
Yes please make a PR, I've used v0.10.0 and I didn't know about the 0.11 issues.

**Comment by perriea** [comment]
Ok, the PR #3 is submitted.
I just noticed that you did not correct the Scaleway provider version. This provider does not evolve quickly but it could be dangerous if Scaleway makes big changes in their API.

I will open a new PR for this purpose.
