### ISSUE TITLE
Prevent kubeadm version mismatches

### ISSUE THREAD

**Issue by stephenmoloney** [stefanprodan/k8s-scw-baremetal#23]
***Issue:***

Kubeadm can be installed at higher versions than kubernetes. Rather than allowing different versions, it may be better to use similar level versions to avoid cluster malfunction.

***Potential solution:***

Pin kubeadm at versions at the same `Major.Minor` level as kubernetes

PR to follow.

#24

**Comment by stefanprodan** [comment]
I also notice this. A PR would be great, thanks @stephenmoloney

**Comment by stephenmoloney** [comment]
Closed with #24
