### ISSUE TITLE
Is custom metrics support for now?

### ISSUE THREAD

**Issue by resouer** [stefanprodan/k8s-scw-baremetal#4]
This is a great work. May I ask is custom metrics support for now?

**Comment by stefanprodan** [comment]
Are you referring to HPA v2 with custom metrics?

**Comment by resouer** [comment]
Right, it would be very useful.

**Comment by stefanprodan** [comment]
I have a separate repo for HPA v2 with Prometheus metrics, here it is https://github.com/stefanprodan/k8s-prom-hpa

**Comment by resouer** [comment]
Thanks!
