### ISSUE TITLE
ping

### ISSUE THREAD

**Issue by alekc** [stefanprodan/k8s-scw-baremetal#45]
Thanks for this repository, helped me a lot. 

Just wanted to ask, is there any particular reason for block of ping? As of now, you can't ping outside of pods (even if they are inbound rules only, I think they are effectively blocking ping reply as well) which can be bit of a headache for debug purposes.

**Comment by stefanprodan** [comment]
You could should use `nc` for debugging

**Comment by alekc** [comment]
Yeah I know, I was just wondering if there was any specific reason for icmp protocol block or if that was just a preference choice
